# تفعيل Remote Desktop
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0

# فتح الجدار الناري
Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

# إنشاء مستخدم RDP
net user RDP "Rdp@2026Secure123" /add
net localgroup administrators RDP /add

# منع انتهاء كلمة المرور
wmic useraccount where name='RDP' set PasswordExpires=FALSE
