- name: Create User
  shell: powershell
  run: |
    $password = "Rdp@$(Get-Random -Minimum 100000 -Maximum 999999)!Aa"

    $secure = ConvertTo-SecureString $password -AsPlainText -Force

    New-LocalUser `
      -Name "RDP" `
      -Password $secure `
      -AccountNeverExpires `
      -PasswordNeverExpires

    Add-LocalGroupMember -Group "Administrators" -Member "RDP"

    echo "RDP_USER=RDP" >> $env:GITHUB_ENV
    echo "RDP_PASS=$password" >> $env:GITHUB_ENV
