# Enable Remote Desktop
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0

# Enable Firewall for RDP
Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

# Create RDP user
net user RDP "Rdp2026Aa12345" /add
net localgroup administrators RDP /add
